# -*- coding: utf-8 -*-
"""Score.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t6LXiTOnObA4S6btYj6pLEaU49_Oy5US
"""

scores = list(map(int, input().split()))
print(max(scores), min(scores))