# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gt9jGQ8WHUTJXggWFnCF0evPf5bwoVpO
"""

scores = list(map(int, input().split()))
print("不及格人數:", sum(1 for s in scores if s < 60))
print("平均數:", sum(scores) / len(scores))