# -*- coding: utf-8 -*-
"""score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gt9jGQ8WHUTJXggWFnCF0evPf5bwoVpO
"""

score = input().split()
failnum=0
sum = 0
for i in score:
  sum += int(i)
  if int(i) < 60:
    failnum = failnum+1
print("不及格人數:",failnum)

scores = []
for i in score:
  scores.append(int(i))

print("最高分:", max(scores))
print("最低分:", min(scores))
l = len(score)
avg = sum / l
print("不及格人數:",failnum)
print("平均數:", avg)